//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agtAgent
    {
        public int agentID { get; set; }
        public Nullable<byte> divisionID { get; set; }
        public Nullable<int> corporationID { get; set; }
        public Nullable<int> locationID { get; set; }
        public Nullable<byte> level { get; set; }
        public Nullable<short> quality { get; set; }
        public Nullable<int> agentTypeID { get; set; }
        public Nullable<bool> isLocator { get; set; }
    }
}
