//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crpNPCCorporationDivision
    {
        public int corporationID { get; set; }
        public byte divisionID { get; set; }
        public Nullable<byte> size { get; set; }
    }
}
