//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crtCertificate
    {
        public int certificateID { get; set; }
        public Nullable<byte> categoryID { get; set; }
        public Nullable<int> classID { get; set; }
        public Nullable<byte> grade { get; set; }
        public Nullable<int> corpID { get; set; }
        public Nullable<int> iconID { get; set; }
        public string description { get; set; }
    }
}
