//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crtRecommendation
    {
        public int recommendationID { get; set; }
        public Nullable<int> shipTypeID { get; set; }
        public Nullable<int> certificateID { get; set; }
        public byte recommendationLevel { get; set; }
    }
}
