//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customPrice
    {
        public int typeID { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> priceDate { get; set; }
    }
}
