//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dgmTypeAttribute
    {
        public int typeID { get; set; }
        public short attributeID { get; set; }
        public Nullable<int> valueInt { get; set; }
        public Nullable<double> valueFloat { get; set; }
    }
}
