//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EveHQDataEntities : DbContext
    {
        public EveHQDataEntities()
            : base("name=EveHQDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<assetItemName> AssetItemNames { get; set; }
        public DbSet<customPrice> CustomPrices { get; set; }
        public DbSet<eveIDToName> EveIDToNames { get; set; }
        public DbSet<eveMail> EveMails { get; set; }
        public DbSet<eveNotification> EveNotifications { get; set; }
        public DbSet<inventionResult> InventionResults { get; set; }
        public DbSet<marketPrice> MarketPrices { get; set; }
        public DbSet<requisition> Requisitions { get; set; }
        public DbSet<walletJournal> WalletJournals { get; set; }
        public DbSet<walletTransaction> WalletTransactions { get; set; }
    }
}
