//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eveNotification
    {
        public string messageKey { get; set; }
        public long messageID { get; set; }
        public long typeID { get; set; }
        public long originatorID { get; set; }
        public long senderID { get; set; }
        public System.DateTime sentDate { get; set; }
        public bool readMail { get; set; }
        public string messageBody { get; set; }
    }
}
