//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invContrabandType
    {
        public int factionID { get; set; }
        public int typeID { get; set; }
        public Nullable<double> standingLoss { get; set; }
        public Nullable<double> confiscateMinSec { get; set; }
        public Nullable<double> fineByValue { get; set; }
        public Nullable<double> attackMinSec { get; set; }
    }
}
