//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventionResult
    {
        public long resultID { get; set; }
        public Nullable<long> jobID { get; set; }
        public Nullable<System.DateTime> resultDate { get; set; }
        public Nullable<int> BPID { get; set; }
        public Nullable<int> typeID { get; set; }
        public string typeName { get; set; }
        public Nullable<long> installerID { get; set; }
        public string installerName { get; set; }
        public Nullable<int> result { get; set; }
    }
}
