//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invFlag
    {
        public short flagID { get; set; }
        public string flagName { get; set; }
        public string flagText { get; set; }
        public Nullable<int> orderID { get; set; }
    }
}
