//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invItem
    {
        public long itemID { get; set; }
        public int typeID { get; set; }
        public int ownerID { get; set; }
        public long locationID { get; set; }
        public short flagID { get; set; }
        public int quantity { get; set; }
    }
}
