//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invPosition
    {
        public long itemID { get; set; }
        public double x { get; set; }
        public double y { get; set; }
        public double z { get; set; }
        public Nullable<float> yaw { get; set; }
        public Nullable<float> pitch { get; set; }
        public Nullable<float> roll { get; set; }
    }
}
