//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapSolarSystem
    {
        public Nullable<int> regionID { get; set; }
        public Nullable<int> constellationID { get; set; }
        public int solarSystemID { get; set; }
        public string solarSystemName { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<double> z { get; set; }
        public Nullable<double> xMin { get; set; }
        public Nullable<double> xMax { get; set; }
        public Nullable<double> yMin { get; set; }
        public Nullable<double> yMax { get; set; }
        public Nullable<double> zMin { get; set; }
        public Nullable<double> zMax { get; set; }
        public Nullable<double> luminosity { get; set; }
        public Nullable<bool> border { get; set; }
        public Nullable<bool> fringe { get; set; }
        public Nullable<bool> corridor { get; set; }
        public Nullable<bool> hub { get; set; }
        public Nullable<bool> international { get; set; }
        public Nullable<bool> regional { get; set; }
        public Nullable<bool> constellation { get; set; }
        public Nullable<double> security { get; set; }
        public Nullable<int> factionID { get; set; }
        public Nullable<double> radius { get; set; }
        public Nullable<int> sunTypeID { get; set; }
        public string securityClass { get; set; }
    }
}
