//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double Sell { get; set; }
        public double Buy { get; set; }
        public int ItemId { get; set; }
        public int SolarSystemId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual SolarSystem SolarSystem { get; set; }
    }
}
