//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ramAssemblyLineType
    {
        public byte assemblyLineTypeID { get; set; }
        public string assemblyLineTypeName { get; set; }
        public string description { get; set; }
        public Nullable<double> baseTimeMultiplier { get; set; }
        public Nullable<double> baseMaterialMultiplier { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<byte> activityID { get; set; }
        public Nullable<double> minCostPerHour { get; set; }
    }
}
