//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ramAssemblyLineTypeDetailPerGroup
    {
        public byte assemblyLineTypeID { get; set; }
        public int groupID { get; set; }
        public Nullable<double> timeMultiplier { get; set; }
        public Nullable<double> materialMultiplier { get; set; }
    }
}
