//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ramAssemblyLineStation
    {
        public int stationID { get; set; }
        public byte assemblyLineTypeID { get; set; }
        public Nullable<byte> quantity { get; set; }
        public Nullable<int> stationTypeID { get; set; }
        public Nullable<int> ownerID { get; set; }
        public Nullable<int> solarSystemID { get; set; }
        public Nullable<int> regionID { get; set; }
    }
}
