//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisition
    {
        public int orderID { get; set; }
        public int itemID { get; set; }
        public string itemName { get; set; }
        public int itemQuantity { get; set; }
        public string source { get; set; }
        public string requestor { get; set; }
        public System.DateTime requestDate { get; set; }
        public string requisition1 { get; set; }
    }
}
