//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class translationTable
    {
        public string sourceTable { get; set; }
        public string destinationTable { get; set; }
        public string translatedKey { get; set; }
        public Nullable<int> tcGroupID { get; set; }
        public Nullable<int> tcID { get; set; }
    }
}
