//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class warCombatZone
    {
        public int combatZoneID { get; set; }
        public string combatZoneName { get; set; }
        public Nullable<int> factionID { get; set; }
        public Nullable<int> centerSystemID { get; set; }
        public string description { get; set; }
    }
}
